Makefile.test.include: Use "make check" tests in parallel

diff --git a/build-aux/run-test.sh.in b/build-aux/run-test.sh.in
--- a/build-aux/run-test.sh.in
+++ b/build-aux/run-test.sh.in
@@ -5,7 +5,33 @@
 set -eu
 
 function get_test_name() {
-  basename "$1"
+  while [ $# -gt 0 ]; do
+    case "$1" in
+      --test-name)
+	echo "$2"
+	return
+	;;
+      *)
+	shift
+	;;
+    esac
+  done
+  echo "Missing --test-name parameter" >&2
+  exit 1
+}
+
+function cat_log_file() {
+  while [ $# -gt 0 ]; do
+    case "$1" in
+      --log-file)
+	cat $2
+	break
+	;;
+      *)
+	shift
+	;;
+    esac
+  done
 }
 
 top_srcdir="@abs_top_srcdir@"
@@ -63,4 +89,5 @@ if test $ret != 0; then
   echo "Failed to run: $@" >&2
 fi
 
+cat_log_file "$@"
 exit $ret
